from django.urls import path
from apps.dashboard.views import (
    DashboardLoginView,
    DashboardLogoutView,
    DashboardForbiddenView,
    DashboardHomeView,
    PoliceHomeView,
    MarkForSubmissionView,
    ForensicHomeView,
    ForensicFlaggedCasesView,
    ForensicChainAuditView,
    ForensicHashReverifyView,
    ForensicEncryptionIntegrityView,
    ForensicTamperLogView,
    ForensicExpertReportPdfView,
    BccHomeView,
    JudiciaryHomeView,
    DashboardCasesView,
    DashboardCaseDetailView,
    DashboardChainVerifyView,
    DashboardCertificatesView,
    DashboardCertificateView,
    DashboardCertificatePdfView,
)

urlpatterns = [
    path("login/", DashboardLoginView.as_view(), name="dashboard-login"),
    path("logout/", DashboardLogoutView.as_view(), name="dashboard-logout"),
    path("forbidden/", DashboardForbiddenView.as_view(), name="dashboard-forbidden"),
    path("", DashboardHomeView.as_view(), name="dashboard-home"),
    path("police/", PoliceHomeView.as_view(), name="dashboard-police-home"),
    path("police/submit/<uuid:vault_id>/", MarkForSubmissionView.as_view(), name="dashboard-mark-submitted"),
    path("forensic/", ForensicHomeView.as_view(), name="dashboard-forensic-home"),
    path("forensic/flagged/", ForensicFlaggedCasesView.as_view(), name="dashboard-forensic-flagged"),
    path("forensic/chain-audit/", ForensicChainAuditView.as_view(), name="dashboard-forensic-chain-audit"),
    path("forensic/reverify/<uuid:vault_id>/", ForensicHashReverifyView.as_view(), name="dashboard-forensic-reverify"),
    path("forensic/integrity/<uuid:vault_id>/", ForensicEncryptionIntegrityView.as_view(), name="dashboard-forensic-integrity"),
    path("forensic/tamper-log/", ForensicTamperLogView.as_view(), name="dashboard-forensic-tamper-log"),
    path("forensic/expert-report/<uuid:vault_id>/", ForensicExpertReportPdfView.as_view(), name="dashboard-forensic-expert-pdf"),
    path("bcc/", BccHomeView.as_view(), name="dashboard-bcc-home"),
    path("judiciary/", JudiciaryHomeView.as_view(), name="dashboard-judiciary-home"),
    path("cases/", DashboardCasesView.as_view(), name="dashboard-cases"),
    path("cases/<uuid:vault_id>/", DashboardCaseDetailView.as_view(), name="dashboard-case-detail"),
    path("chain/", DashboardChainVerifyView.as_view(), name="dashboard-chain-verify"),
    path("certificates/", DashboardCertificatesView.as_view(), name="dashboard-certificates"),
    path("certificates/<uuid:vault_id>/", DashboardCertificateView.as_view(), name="dashboard-certificate"),
    path("certificates/<uuid:vault_id>/pdf/", DashboardCertificatePdfView.as_view(), name="dashboard-certificate-pdf"),
]