# Generated by Django 6.0.2 on 2026-02-27 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('vault_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique vault identifier. Used as the filename in BCC storage.', primary_key=True, serialize=False)),
                ('file_hash', models.CharField(help_text='SHA-256 hash generated on the mobile device at point of capture.', max_length=64)),
                ('storage_path', models.CharField(help_text='Path to the file inside the BCC National Data Center (MinIO).', max_length=500)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes, recorded at upload.', null=True)),
                ('file_mime_type', models.CharField(blank=True, help_text='MIME type e.g. image/jpeg, video/mp4', max_length=100, null=True)),
                ('is_encrypted', models.BooleanField(default=True, help_text='True if the stored file is AES-256-GCM encrypted.')),
                ('encryption_nonce', models.BinaryField(blank=True, help_text='AES-GCM nonce (IV) used during encryption. Unique per file.', max_length=12, null=True)),
                ('is_compressed', models.BooleanField(default=True, help_text='True if the file was gzip-compressed before encryption.')),
                ('original_size_bytes', models.PositiveBigIntegerField(blank=True, help_text='Original uncompressed, unencrypted file size in bytes.', null=True)),
                ('stored_size_bytes', models.PositiveBigIntegerField(blank=True, help_text='Actual size stored in MinIO after compression and encryption.', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude at time of capture (hardware-level).', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude at time of capture (hardware-level).', max_digits=9, null=True)),
                ('captured_at', models.DateTimeField(help_text='Network-synchronized timestamp from the mobile device at capture.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Server-side timestamp when evidence was ingested into the vault.')),
                ('evidence_type', models.CharField(choices=[('photo', 'Photograph'), ('video', 'Video Recording'), ('audio', 'Audio Recording'), ('screenshot', 'Screenshot'), ('document', 'Document')], default='photo', max_length=20)),
                ('harm_type', models.CharField(choices=[('sextortion', 'Sextortion'), ('image_abuse', 'Image-Based Abuse'), ('doxxing', 'Doxxing'), ('cyberbullying', 'Cyberbullying'), ('harassment', 'Online Harassment'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, help_text="Victim's own description of the incident.", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified & Sealed'), ('flagged', 'Flagged - Integrity Issue'), ('submitted', 'Submitted to Court')], default='pending', max_length=20)),
                ('is_hash_verified', models.BooleanField(default=False, help_text='True when server-side re-hash matches the mobile-submitted hash.')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the verification was performed.', null=True)),
                ('device_id', models.CharField(blank=True, help_text='Anonymised hardware identifier of the capture device.', max_length=200, null=True)),
                ('app_version', models.CharField(blank=True, help_text='Version of the Nirvhoy Flutter app used for capture.', max_length=20, null=True)),
                ('reporter', models.ForeignKey(help_text='The NID-verified user who submitted this evidence.', on_delete=django.db.models.deletion.PROTECT, related_name='evidence_reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Police officer or forensic analyst who verified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence Record',
                'verbose_name_plural': 'Evidence Records',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['reporter', 'status'], name='evidence_ev_reporte_da5fb6_idx'), models.Index(fields=['file_hash'], name='evidence_ev_file_ha_b595be_idx'), models.Index(fields=['uploaded_at'], name='evidence_ev_uploade_01a06d_idx')],
            },
        ),
    ]
