# Generated by Django 6.0.2 on 2026-02-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_phase1_upazila_verdict_purgerequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evidence',
            new_name='evidence_ev_assigne_6d04ac_idx',
            old_name='evidence_ev_assigne_4a8c2d_idx',
        ),
    ]
