# Generated by Django 6.0.2 on 2026-02-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='testimonial_voice_path',
            field=models.CharField(blank=True, help_text='S3 path to voice testimonial file (e.g. report/testimonials/YYYY/MM/<id>_voice.*).', max_length=500),
        ),
    ]
