# Generated by Django 6.0.2 on 2026-02-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_testimonial_voice_path'),
        ('report', '0002_report_status'),
    ]

    operations = [
    ]
