# Generated by Django 6.0.2 on 2026-02-27 20:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_hash', models.CharField(help_text="Hash of the previous block. '000...0' for genesis.", max_length=64)),
                ('block_hash', models.CharField(help_text="SHA-256 hash of this block's data + previous_hash.", max_length=64, unique=True)),
                ('block_number', models.PositiveIntegerField(help_text='Sequential block number. Genesis = 0.', unique=True)),
                ('event_type', models.CharField(choices=[('capture', 'Initial Capture'), ('vault_ingest', 'Vault Ingestion'), ('access', 'Evidence Accessed'), ('verification', 'Hash Verified'), ('transfer', 'Transferred to Court'), ('genesis', 'Genesis Block')], default='capture', max_length=20)),
                ('evidence_hash_snapshot', models.CharField(blank=True, help_text='Snapshot of Evidence.file_hash at the time of sealing.', max_length=64, null=True)),
                ('actor_user_id', models.CharField(blank=True, help_text='UUID of the user who triggered this event.', max_length=100, null=True)),
                ('actor_role', models.CharField(blank=True, help_text='Role of the actor (victim, police, analyst).', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Human-readable description of this event.', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this block was sealed.')),
                ('evidence', models.ForeignKey(blank=True, help_text='The evidence record this block is sealing.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blockchain_logs', to='evidence.evidence')),
            ],
            options={
                'verbose_name': 'Forensic Log (Blockchain Block)',
                'verbose_name_plural': 'Forensic Log (Blockchain)',
                'ordering': ['block_number'],
            },
        ),
    ]
