# Generated by Django 6.0.2 on 2026-02-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forensiclog',
            name='event_type',
            field=models.CharField(choices=[('capture', 'Initial Capture'), ('vault_ingest', 'Vault Ingestion'), ('access', 'Evidence Accessed'), ('verification', 'Hash Verified'), ('transfer', 'Transferred to Court'), ('verdict', 'Verdict Recorded'), ('genesis', 'Genesis Block')], default='capture', max_length=20),
        ),
    ]
