# Generated by Django 6.0.2 on 2026-02-27 19:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nid_hash', models.CharField(blank=True, help_text='SHA-256 hash of the National ID number. Raw NID is never stored.', max_length=64, null=True, unique=True)),
                ('nid_verified', models.BooleanField(default=False, help_text='True only after successful biometric check via NIDW Partner API.')),
                ('role', models.CharField(choices=[('victim', 'Victim / Reporter'), ('police', 'Police Officer'), ('forensic_analyst', 'Forensic Analyst'), ('bcc_admin', 'BCC / System Admin'), ('judiciary', 'Judiciary / Magistrate')], default='victim', max_length=20)),
                ('police_badge_id', models.CharField(blank=True, help_text='Official police badge ID. Only populated for police role.', max_length=50, null=True)),
                ('assigned_upazila', models.CharField(blank=True, help_text='The upazila this officer is assigned to.', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Primary contact number (BD format: +880XXXXXXXXXX).', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Nirvhoy User',
                'verbose_name_plural': 'Nirvhoy Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
